# PROJECT 

CREATE DATABASE PIZZAHUT;
USE PIZZAHUT;
SELECT * FROM PIZZAHUT.pizzas;
SELECT * FROM PIZZAHUT.pizza_types;
SELECT * FROM PIZZAHUT.orders;

# NOW CREATING A TABLE FOR ORDER 
CREATE TABLE ORDERS(
ORDER_ID INT NOT NULL,
ORDER_DATE DATE NOT NULL ,
ORDER_TIME TIME NOT NULL,
PRIMARY KEY (ORDER_ID));

# NOW CREATE A TABLE FOR ORDER DETAILS 
CREATE TABLE ORDER_DETAILS(
ORDER_DETAILS_ID INT NOT NULL,
ORDER_ID INT NOT NULL ,
PIZZA_ID TEXT NOT NULL,
QUANTITY INT NOT NULL,
PRIMARY KEY (ORDER_DETAILS_ID));

