-- NOW AFTER IMPORTING THE DATA NOW SOLVE THE QUESTION

 -- Q1 RETRIVE THE TOTAL NUMBER OF ORDER PLACED 
  SELECT COUNT(ORDER_ID) AS TOTA_ORDERS FROM ORDERS;
  
  -- Q2 CALCULATED TOTAL REVENUE GENERATED FROM PIZZA SALES 
  SELECT 
    ROUND(SUM(ORDER_DETAILS.QUANTITY * PIZZAS.PRICE),
            2) AS TOTAL_SALES
FROM
    ORDER_DETAILS
        JOIN
    PIZZAS ON PIZZAS.PIZZA_ID = ORDER_DETAILS.PIZZA_ID;
    
-- Q3 IDENTIFY THE HIGHEST PRIZE PIZZA 
SELECT PIZZA_TYPES.NAME,PIZZAS.PRICE
FROM PIZZA_TYPES JOIN PIZZAS
ON PIZZA_TYPES.PIZZA_TYPE_ID = PIZZAS.PIZZA_TYPE_ID
ORDER BY PIZZAS.PRICE DESC LIMIT 1;

-- Q4 IDENTIFY THE MOST PIZZA SIZE COMMONLY ORDERD
SELECT PIZZAS.SIZE,COUNT(ORDER_DETAILS.ORDER_DETAILS_ID) AS ORDER_COUNT
FROM PIZZAS JOIN ORDER_DETAILS
ON PIZZAS.PIZZA_ID = ORDER_DETAILS.PIZZA_ID
GROUP BY PIZZAS.SIZE ORDER BY ORDER_COUNT DESC;

-- Q5 LIST THE TOP 5 MOST ORDERD PIZZA TYPES ALONG WITH THEIR QUANTITIES 
SELECT PIZZA_TYPES.NAME,
SUM(ORDER_DETAILS.QUANTITY) AS QUANTITY
FROM PIZZA_TYPES JOIN PIZZAS
ON PIZZA_TYPES.PIZZA_TYPE_ID = PIZZAS.PIZZA_TYPE_ID
JOIN ORDER_DETAILS
ON ORDER_DETAILS.PIZZA_ID = PIZZAS.PIZZA_ID
GROUP BY PIZZA_TYPES.NAME ORDER BY QUANTITY DESC LIMIT 5 ;

-- Q6 JOIN THE NECESSARY TABLES TO FIND THE TOTAL QUANTITY OF EACH PIZZA CATEGORY ORDER 
SELECT PIZZA_TYPES.CATEGORY,
SUM(ORDER_DETAILS.QUANTITY)AS QUANTITY
FROM PIZZA_TYPES JOIN PIZZAS
ON PIZZA_TYPES.PIZZA_TYPE_ID = PIZZAS.PIZZA_TYPE_ID
JOIN ORDER_DETAILS
ON ORDER_DETAILS.PIZZA_ID = PIZZAS.PIZZA_ID
GROUP BY PIZZA_TYPES.CATEGORY ORDER BY QUANTITY DESC;

-- Q7 DETERMINE THE DISTRIBUTION OF ORDERS BY HOUR OF THE DAY 
SELECT HOUR (ORDER_TIME) AS HOUR,COUNT(ORDER_ID)AS ORDER_COUNT FROM ORDERS
GROUP BY HOUR (ORDER_TIME);

-- Q8 JOIN RELEVENT TABLES TO FIND THE CATEGORY WISE DISTRIBUTION OF PIZZAS 
SELECT CATEGORY , COUNT(NAME) FROM PIZZA_TYPES
GROUP BY CATEGORY;

-- Q9 GROUP THE ORDERS BY DATA AND CALCULATE THE AVERAGE NUMBER OF PIZZAS ORDER PER DAY 
SELECT AVG (QUANTITY) FROM
(SELECT ORDERS.ORDER_DATE,SUM(ORDER_DETAILS.QUANTITY) AS QUANTITY
FROM ORDERS JOIN ORDER_DETAILS
ON ORDERS.ORDER_ID = ORDER_DETAILS.ORDER_ID
GROUP BY ORDERS.ORDER_DATE )AS ORDER_QUANTITY;

-- Q10 TOP 3 MOST ORDERED PIZZA TYPES BASED ON REVENUE 
SELECT PIZZA_TYPES.NAME,
SUM(ORDER_DETAILS.QUANTITY*PIZZAS.PRICE) AS REVENUE
FROM PIZZA_TYPES JOIN PIZZAS
ON PIZZAS.PIZZA_TYPE_ID = PIZZA_TYPES.PIZZA_TYPE_ID
JOIN ORDER_DETAILS
ON ORDER_DETAILS.PIZZA_ID = PIZZAS.PIZZA_ID
GROUP BY PIZZA_TYPES.NAME ORDER BY REVENUE DESC LIMIT 3;













