# default value 
# insert a default value in the table 

CREATE DATABASE EMPLOYEE;
USE EMPLOYEE;

CREATE TABLE INCOME(
	ID INT,
	SALARY INT DEFAULT 25000);
    
# THIS FUNCTION IS USED TO INSERT A DEFAULT VALUE 

INSERT INTO INCOME (ID) VALUES (101);

SELECT * FROM INCOME;
