# creating a sample data base 

CREATE DATABASE UNIVERSITY;
USE UNIVERSITY;

CREATE TABLE STUDENT(
ROLLNO INT PRIMARY KEY ,
NAME VARCHAR(50),
MARKS INT NOT NULL,
GRADE VARCHAR(1),
CITY VARCHAR(20)
);

SELECT * FROM STUDENT;

INSERT INTO STUDENT
(ROLLNO,NAME,MARKS,GRADE,CITY)
VALUES
(101,'ANIL',78,'C','PUNE'),
(102,'NAZIM',96,'A','MUMBAI'),
(103,'CHETAN',85,'B','MUMBAI'),
(104,'DHRUV',96,'A','DELHI'),
(105,'KHAN',12,'F','DELHI'),
(106,'FARAH',82,'B','DELHI');


# STUDY ABOUT SELECT 

SELECT DISTINCT CITY FROM STUDENT;

# WHERE CLAUSE 

SELECT * FROM STUDENT WHERE MARKS >=80;

SELECT * FROM STUDENT WHERE CITY = 'MUMBAI';

SELECT * FROM STUDENT WHERE MARKS >=80 AND CITY = 'MUMBAI';


# OPERATORS ON SQL 
SELECT * FROM STUDENT WHERE MARKS+10 >100;

SELECT * FROM STUDENT WHERE MARKS = 96;

SELECT * FROM STUDENT WHERE MARKS >80 AND CITY = 'MUMBAI';

SELECT * FROM STUDENT WHERE MARKS >90 OR CITY = 'DELHI';

SELECT * FROM STUDENT WHERE MARKS BETWEEN 80 AND 90;

SELECT * FROM STUDENT WHERE CITY IN ('DELHI','MUMBAI');

SELECT * FROM STUDENT WHERE CITY NOT IN ('DELHI','MUMBAI');


# LIMIT CLAUSE 
SELECT * FROM STUDENT LIMIT 2;

SELECT * FROM STUDENT WHERE MARKS >75 LIMIT 3;

# ORDER BY CLAUSE 
SELECT * FROM STUDENT ORDER BY CITY ASC LIMIT 3;

SELECT * FROM STUDENT ORDER BY CITY DESC;

# AGGREGATE FUNCTION 

SELECT MAX(MARKS) FROM STUDENT;
SELECT MIN(MARKS) FROM STUDENT;

SELECT COUNT(NAME) FROM STUDENT;
SELECT AVG (MARKS) FROM STUDENT;

# GROUP BY CLAUSE 

SELECT CITY,AVG (MARKS) FROM STUDENT GROUP BY CITY;


# PRACTICE QUESTION 

SELECT CITY,AVG(MARKS)
FROM STUDENT
GROUP BY CITY
ORDER BY CITY DESC;

# HAVING CLAUSE 

SELECT COUNT(NAME),CITY FROM STUDENT
GROUP BY CITY HAVING MAX(MARKS)>90;


SELECT CITY
FROM STUDENT
WHERE GRADE = 'A'
GROUP BY CITY 
HAVING MAX(MARKS) >=90
ORDER BY CITY DESC;


# TABLE RELATED QUARRY 
# UPDATE 
SET SQL_SAFE_UPDATES = 0;

UPDATE STUDENT
SET GRADE = 'O'
WHERE GRADE = 'A';

UPDATE STUDENT
SET GRADE = 'B'
WHERE MARKS  BETWEEN 80 AND 90;

SELECT * FROM STUDENT;


# DELETE 
DELETE FROM STUDENT 
WHERE MARKS <33






