# PRACTICE QUESTON 
# CHANGE THE NAME OF COLUMN NAME TO FULL-NAME
# DELETE ALL THE STUDENT WHO SCORED MARKS LESS THAN 80
# DELETE THE COLUMN FOR GRADES


CREATE DATABASE DETAILS;
USE DETAILS;

CREATE TABLE INFO(
ROLLNO INT PRIMARY KEY ,
NAME VARCHAR(50),
MARKS INT NOT NULL,
GRADE VARCHAR(1),
CITY VARCHAR(20)
);

INSERT INTO INFO
(ROLLNO,NAME,MARKS,GRADE,CITY)
VALUES
(101,'ANIL',78,'C','PUNE'),
(102,'NAZIM',96,'A','MUMBAI'),
(103,'CHETAN',85,'B','MUMBAI'),
(104,'DHRUV',96,'A','DELHI'),
(105,'KHAN',12,'F','DELHI'),
(106,'FARAH',82,'B','DELHI');

SELECT *  FROM INFO;

ALTER TABLE INFO
CHANGE NAME FULL_NAME VARCHAR(50);

DELETE FROM INFO
WHERE MARKS <80;

ALTER TABLE INFO
DROP COLUMN GRADE;