# sets----------------- 

# union---------------------------
SELECT NAME FROM CHILDERN;
UNION

SELECT NAME FROM CHILDERN;


SELECT NAME FROM CHILDERN;
UNION ALL
SELECT NAME FROM CHILDERN;

#---------------------
# view -----

SELECT * FROM STUDENT;
CREATE VIEW VIEW1 AS 
SELECT ROLLNO,NAME,MARKS,FROM STUDENT;
SELECT*FROM VIEW1